language: php
php:
  - 5.6
  - 5.5
  - 5.4
before_script: echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install
script:
  - vendor/bin/phpunit
